#!/usr/bin/env bash

set -eu

url_metplus=<METPLUS_URL> # replaced during package build

get() {
  (
    mkdir -pv $2
    set -x
    curl -LSs $1 | tar xvz --strip-components=2 -C $2 $3
  )
}

ver() {
  echo $1 | sed -E 's@^.*/v([0-9]+\.[0-9]+\.[0-9]+).*@\1@'
}

echo Installing METplus data:
get $url_metplus $METPLUS_PARM_BASE METplus-$(ver $url_metplus)/parm/
