# {% set nceplibs_g2c = "nceplibs-g2c 1.9.*" %}
# {% set netcdf4 = "netcdf4 1.7.*" %}
# {% set numpy = "numpy 2.2.*" %}
# {% set pandas = "pandas 2.2.*" %}
# {% set xarray = "xarray 2025.12.*" %}

# {% set urls = load_file_data("urls.json", from_recipe_dir=True) %}

package:
  name: met2go
  version: 12.2.1
source:
#   - folder: bufr
#     sha256: 946482405e675b99e8e0c221d137768f246076f5e9ba92eed6cae47fb68b7a26
#     url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/bufr_v11.4.0.tar.gz

  - folder: met
    sha256: 3ad18c37dabf185ea97839a8093cebbfa7e6a2ba7ab92081a0a797f6d5181d8f
    url: https://dtcenter.ucar.edu/dfiles/code/METplus/MET/installation/tar_files.tgz
#   - folder: met
#     sha256: 8c3d426df4c9b932c1853518085f9f0d5fda0df076bb5adebc88901a828f308f
#     url: https://github.com/dtcenter/MET/archive/refs/tags/v12.2.1.tar.gz
  - folder: met
    sha256: 77995e73593d8e006aeef21fe30d21192e3bf9814f1bb9d7bcd58cbbf4cc1c04
    url: https://raw.githubusercontent.com/dtcenter/MET/refs/heads/main_v12.2/internal/scripts/installation/compile_MET_all.sh

#   - folder: netcdf-cxx
#     sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
#     url: https://github.com/Unidata/netcdf-cxx4/archive/refs/tags/v4.3.1.tar.gz
build:
#   ignore_run_exports:
#     - jasper
#     - netcdf4
#     - numpy
#     - pandas
#     - python-dateutil
#     - xarray
  include_recipe: false
  number: 1
requirements:
  build:
#     - cmake 3.*
#     - curl
#     - jq
#     - make
#     - pip
#     - pkgconfig
#     - python
#     - rsync
#     - setuptools
    - wget
    - {{ compiler("c") }}
#     - {{ compiler("cxx") }}
#     - {{ compiler("fortran") }}
#   host:
#     - _openmp_mutex # [linux]
#     - gsl 2.8
#     - jasper 4.2.*
#     - libnetcdf 4.9.2.*
#     - libopenblas 0.3.*
#     - python
#     - zlib 1.3.*
#     - {{ nceplibs_g2c }}
#     - {{ netcdf4 }}
#     - {{ numpy }}
#     - {{ pandas }}
#     - {{ xarray }}
#   run:
#     - cartopy
#     - imagemagick
#     - matplotlib
#     - plotly >=6.0
#     - python
#     - python-dateutil
#     - python-kaleido >=0.2
#     - pyyaml >=6.0
#     - scipy >=1.15
#     - {{ nceplibs_g2c }}
#     - {{ netcdf4 }}
#     - {{ numpy }}
#     - {{ pandas }}
#     - {{ xarray }}
about:
  home: https://github.com/maddenp/met2go
  license: APACHE
