{% set libopenblas = "libopenblas 0.3.*" %}
{% set nceplibs_g2c = "nceplibs-g2c 1.9.*" %}
{% set netcdf4 = "netcdf4 1.7.*" %}
{% set numpy = "numpy 2.2.*" %}
{% set pandas = "pandas 2.2.*" %}
{% set xarray = "xarray 2025.1.*" %}

package:
  name: met2go
  version: 11.0.3
source:
  - folder: bufr
    sha256: 946482405e675b99e8e0c221d137768f246076f5e9ba92eed6cae47fb68b7a26
    url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/bufr_v11.4.0.tar.gz
  - folder: met
    sha256: d99272c074c60d3011d0e47bede330ae8adc15f64d403480d8216815cbff7e7a
    url: https://github.com/dtcenter/MET/archive/refs/tags/v11.0.3.tar.gz
  - folder: metcalcpy
    sha256: 41ad136683152265df80e27af49bac27e0d8d06606d1201aa1ffe215552640bf
    url: https://github.com/dtcenter/METcalcpy/archive/refs/tags/v3.0.0.tar.gz
  - folder: metdataio
    sha256: 442ff4b541433aa2886b5ceaf9f1d2e646a7f66427981fff5d7f7fdd75f7eb30
    url: https://github.com/dtcenter/METdataio/archive/refs/tags/v3.0.0.tar.gz
  - folder: metplotpy
    sha256: 50a04a06a9bcb7583e1923a94c578436a15adc2cd5a5242a0566992785e89bce
    url: https://github.com/dtcenter/METplotpy/archive/refs/tags/v3.0.0.tar.gz
  - folder: metplus
    patch: patch.metplus
    sha256: e80df2d1059176a453b7991a9f123cb5a187cc7ba7f48a75313b92c7a0e68474
    url: https://github.com/dtcenter/METplus/archive/refs/tags/v5.1.0.tar.gz
  - folder: netcdf-cxx
    sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
    url: https://github.com/Unidata/netcdf-cxx4/archive/refs/tags/v4.3.1.tar.gz
build:
  ignore_run_exports:
    - jasper
    - netcdf4
    - numpy
    - pandas
    - python-dateutil
    - xarray
  include_recipe: false
  number: 0
requirements:
  build:
    - cmake
    - make
    - pip
    - pkgconfig
    - python
    - setuptools
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - _openmp_mutex # [linux]
    - gsl 2.8
    - jasper 4.2.*
    - libnetcdf 4.9.*
    - python
    - zlib 1.3.*
    - {{ libopenblas }}
    - {{ nceplibs_g2c }}
    - {{ netcdf4 }}
    - {{ numpy }}
    - {{ pandas }}
    - {{ xarray }}
  run:
    - cartopy
    - imagemagick
    - matplotlib
    - plotly >=6.0
    - python
    - python-dateutil
    - python-kaleido >=0.2
    - pyyaml >=6.0
    - scipy >=1.15
    - {{ libopenblas }}
    - {{ nceplibs_g2c }}
    - {{ netcdf4 }}
    - {{ numpy }}
    - {{ pandas }}
    - {{ xarray }}
about:
  home: https://github.com/maddenp/met2go
  license: APACHE
