{% set g2c = "nceplibs-g2c 1.9.*" %}
{% set netcdf4 = "netcdf4 1.7.*" %}
{% set numpy = "numpy 1.22.*" %}
{% set pandas = "pandas 2.2.*" %}
{% set python = "python >=3.10.*" %}
{% set xarray = "xarray 2023.12.*" %}

package:
  name: metkit
  version: 11.0.3
source:
  - folder: bufr
    sha256: 946482405e675b99e8e0c221d137768f246076f5e9ba92eed6cae47fb68b7a26
    url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/bufr_v11.4.0.tar.gz
  - folder: met
    sha256: d99272c074c60d3011d0e47bede330ae8adc15f64d403480d8216815cbff7e7a
    url: https://github.com/dtcenter/MET/archive/refs/tags/v11.0.3.tar.gz
  - folder: metplus
    patch: patch.metplus
    sha256: e80df2d1059176a453b7991a9f123cb5a187cc7ba7f48a75313b92c7a0e68474
    url: https://github.com/dtcenter/METplus/archive/refs/tags/v5.1.0.tar.gz
  - folder: netcdf-cxx
    sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
    url: https://github.com/Unidata/netcdf-cxx4/archive/refs/tags/v4.3.1.tar.gz
build:
  ignore_run_exports:
    - jasper
    - libopenblas
    - netcdf4
    - numpy
    - pandas
    - python
    - python-dateutil
    - xarray
  include_recipe: false
  number: 0
requirements:
  build:
    - cmake 3.30.*
    - make 4.4.*
    - pip
    - pkgconfig 1.5.*
    - setuptools
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - _openmp_mutex 4.5
    - gsl 2.7
    - jasper 4.2.*
    - libnetcdf 4.9.*
    - libopenblas 0.3.*
    - zlib 1.3.*
    - {{ g2c }}
    - {{ netcdf4 }}
    - {{ numpy }}
    - {{ pandas }}
    - {{ python }}
    - {{ xarray }}
  run:
    - cartopy 0.21.*
    - imagemagick 7.1.*
    - matplotlib 3.5.*
    - python-dateutil 2.8.*
    - {{ g2c }}
    - {{ netcdf4 }}
    - {{ numpy }}
    - {{ pandas }}
    - {{ python }}
    - {{ xarray }}
about:
  home: FIXME
  license: APACHE
