#!/bin/bash

declare -A os=(["GNU/Linux"]="Linux" ["Darwin"]="MacOSX")

miniforge_version=24.7.1-2
miniforge_fn=Miniforge3-$miniforge_version-${os[$(uname -o)]}-$(uname -m).sh
miniforge_url=https://github.com/conda-forge/miniforge/releases/download/$miniforge_version/$miniforge_fn

activate() {
  . conda/etc/profile.d/conda.sh
  conda activate
}

test ! $(which curl) && echo "Could not find curl" && exit 1

if [[ ! -d conda ]]; then
  mkdir -p conda
  curl -L -o conda/$miniforge_fn $miniforge_url
  bash conda/$miniforge_fn -bfp conda
  activate
  conda install -y anaconda-client conda-build
  conda config --file conda/.condarc --set anaconda_upload yes
fi

activate
make package
