#!/usr/bin/env bash

set -euo pipefail

declare -A os=(["GNU/Linux"]="Linux" ["Darwin"]="MacOSX")

miniforge_version=26.5.3-0
miniforge_fn=Miniforge3-$miniforge_version-${os[$(uname -o)]}-$(uname -m).sh
miniforge_url=https://github.com/conda-forge/miniforge/releases/download/$miniforge_version/$miniforge_fn

activate() {
  . conda/etc/profile.d/conda.sh
  conda activate
}

if [[ -d conda ]]; then
  activate
else
  mkdir -p conda
  apt update && apt install -y curl # PM FIXME
  test ! $(which curl) && echo "Could not find curl" && exit 1
  curl --location --show-error --silent --output conda/$miniforge_fn $miniforge_url
  bash conda/$miniforge_fn -bfp conda
  activate
  conda install --yes conda-build
  conda config --file conda/.condarc --set anaconda_upload no
fi

export PYTHONWARNINGS="ignore:The environment variable:UserWarning:conda_build.environ"
conda build purge
conda build --error-overlinking --build-only --dirty recipe
